version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.15
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@0.0.8
workflows:
  build-and-deploy-dev:
    jobs:
      - aws-ecr/build-and-push-image:
          context: development
          filters:
            branches:
              only: create_circleci_config_yml
          account-url: AWS_ECR_ACCOUNT_URL
          dockerfile: "Dockerfile"
          repo: "sellgo-website"
          region: AWS_REGION
          tag: "${CIRCLE_SHA1}"
          extra-build-args: '--build-arg MODE=local'
      - aws-ecs/deploy-service-update:
          context: development
          filters:
            branches:
              only: create_circleci_config_yml
          requires:
            - aws-ecr/build-and-push-image
          aws-region: ${AWS_REGION}
          cluster-name: "sellgo-ecs"
          family: "sellgo-website"
          container-image-name-updates: "container=sellgo-website,tag=${CIRCLE_SHA1},container=sellgo-website-nginx,image=caprover/nginx-reverse-proxy"
  build-and-deploy-prod:
    jobs:
      - aws-ecr/build-and-push-image:
          context: production
          filters:
            branches:
              only: master
          account-url: AWS_ECR_ACCOUNT_URL
          dockerfile: "Dockerfile"
          repo: "sellgo-website"
          region: AWS_REGION
          tag: "${CIRCLE_SHA1}"
          extra-build-args: '--build-arg MODE=production'
      - aws-ecs/deploy-service-update:
          context: production
          filters:
            branches:
              only: master
          requires:
            - aws-ecr/build-and-push-image
          aws-region: ${AWS_REGION}
          cluster-name: "sellgo-ecs"
          family: "sellgo-website"
          container-image-name-updates: "container=sellgo-website,tag=${CIRCLE_SHA1},container=sellgo-website-nginx,image=caprover/nginx-reverse-proxy"
