export const SELLER_BUSINESS_MODEL_OPTIONS: {value: string, text: string, key: string}[] = [
    {value: 'Amazon 3P Private Label Seller', text: 'Amazon 3P Private Label Seller', key: 'Amazon 3P Private Label Seller'},
    {value: 'Amazon 1P Vendor', text: 'Amazon 1P Vendor', key: 'Amazon 1P Vendor'},
    {value: 'Amazon Wholesaler', text: 'Amazon Wholesaler', key: 'Amazon Wholesaler'},
    {value: 'Direct-to-consumer Brands', text: 'Direct-to-consumer Brands', key: 'Direct-to-consumer Brands'},
    {value: 'Walmart Sellers', text: 'Walmart Sellers', key: 'Walmart Sellers'},
    {value: 'Dropshipping Sellers', text: 'Dropshipping Sellers', key: 'Dropshipping Sellers'},
    {value: 'Other (please explain in message)', text: 'Other (please explain in message)', key: 'Other (please explain in message)'},
];

export const SELLER_COUNTRY_OPTIONS: {value: string, text: string, key: string}[] = [
    {value: 'USA - all states', text: 'USA - all states', key: 'USA - all states'},
    {value: 'China', text: 'China', key: 'China'},
    {value: 'Canada', text: 'Canada', key: 'Canada'},
    {value: 'Mexico', text: 'Mexico', key: 'Mexico'},
    {value: 'Europe', text: 'Europe', key: 'Europe'},
    {value: 'India', text: 'India', key: 'India'},
    {value: 'UAE', text: 'UAE', key: 'UAE'},
    {value: 'Saudi Arabia', text: 'Saudi Arabia', key: 'Saudi Arabia'},
    {value: 'Brazil', text: 'Brazil', key: 'Brazil'},
    {value: 'Australia', text: 'Australia', key: 'Australia'},
    {value: 'Singapore', text: 'Singapore', key: 'Singapore'},
    {value: 'Japan', text: 'Japan', key: 'Japan'},
    {value: 'Other (please explain in message)', text: 'Other (please explain in message)', key: 'Other (please explain in message)'},
];

export const SELLER_MARKETPLACE_OPTIONS: {value: string, text: string, key: string}[] = [
    {value: 'USA - all states', text: 'USA - all states', key: 'USA - all states'},
    {value: 'China', text: 'China', key: 'China'},
    {value: 'Canada', text: 'Canada', key: 'Canada'},
    {value: 'Mexico', text: 'Mexico', key: 'Mexico'},
    {value: 'Europe', text: 'Europe', key: 'Europe'},
    {value: 'India', text: 'India', key: 'India'},
    {value: 'UAE', text: 'UAE', key: 'UAE'},
    {value: 'Saudi Arabia', text: 'Saudi Arabia', key: 'Saudi Arabia'},
    {value: 'Brazil', text: 'Brazil', key: 'Brazil'},
    {value: 'Australia', text: 'Australia', key: 'Australia'},
    {value: 'Singapore', text: 'Singapore', key: 'Singapore'},
    {value: 'Japan', text: 'Japan', key: 'Japan'},
    {value: 'Other (please explain in message)', text: 'Other (please explain in message)', key: 'Other (please explain in message)'},
];

export const SELLER_DOMINANT_PRODUCT_CATEGORY_OPTIONS: {value: string, text: string, key: string}[] = [
    {value: 'Clothing, shoes & jewelry', text: 'Clothing, shoes & jewelry', key: 'Clothing, shoes & jewelry'},
    {value: 'Automotive', text: 'Automotive', key: 'Automotive'},
    {value: 'Books', text: 'Books', key: 'Books'},
    {value: 'Home & kitchen', text: 'Home & kitchen', key: 'Home & kitchen'},
    {value: 'Tools & home improvement', text: 'Tools & home improvement', key: 'Tools & home improvement'},
    {value: 'Electronics', text: 'Electronics', key: 'Electronics'},
    {value: 'Sports & outdoors', text: 'Sports & outdoors', key: 'Sports & outdoors'},
    {value: 'Industrial & scientific', text: 'Industrial & scientific', key: 'Industrial & scientific'},
    {value: 'Beauty & personal care', text: 'Beauty & personal care', key: 'Beauty & personal care'},
    {value: 'CDs & vinyl', text: 'CDs & vinyl', key: 'CDs & vinyl'},
    {value: 'Toys & games', text: 'Toys & games', key: 'Toys & games'},
    {value: 'Baby products', text: 'Baby products', key: 'Baby products'},
    {value: 'Health & household', text: 'Health & household', key: 'Health & household'},
    {value: 'Patio, lawn & garden', text: 'Patio, lawn & garden', key: 'Patio, lawn & garden'},
    {value: 'Musical instruments', text: 'Musical instruments', key: 'Musical instruments'},
    {value: 'Handmade products', text: 'Handmade products', key: 'Handmade products'},
    {value: 'Grocery & gourmet food', text: 'Grocery & gourmet food', key: 'Grocery & gourmet food'},
    {value: 'Arts, crafts & sewing', text: 'Arts, crafts & sewing', key: 'Arts, crafts & sewing'},
    {value: 'Office products', text: 'Office products', key: 'Office products'},
    {value: 'Cell phones & accsesories', text: 'Cell phones & accsesories', key: 'Cell phones & accsesories'},
    {value: 'Apps & games', text: 'Apps & games', key: 'Apps & games'},
    {value: 'Video games', text: 'Video games', key: 'Video games'},
    {value: 'Appliances', text: 'Appliances', key: 'Appliances'},
    {value: 'Movies & TV', text: 'Movies & TV', key: 'Movies & TV'},
    {value: 'Pet supplies', text: 'Pet supplies', key: 'Pet supplies'},
    {value: 'Jewelry', text: 'Jewelry', key: 'Jewelry'},
    {value: 'Software', text: 'Software', key: 'Software'},
    {value: 'Collectible & fine art', text: 'Collectible & fine art', key: 'Collectible & fine art'},
    {value: 'Watches', text: 'Watches', key: 'Watches'},
    {value: 'Magazine subscriptions', text: 'Magazine subscriptions', key: 'Magazine subscriptions'},
];

export const SELLER_DATAPOINT_OPTIONS: {value: string, text: string, key: string}[] = [
    {value: 'Contact person', text: 'Contact person', key: 'Contact person'},
    {value: 'Position', text: 'Position', key: 'Position'},
    {value: 'Website', text: 'Website', key: 'Website'},
    {value: 'Personal email', text: 'Personal email', key: 'Personal email'},
    {value: 'Company email', text: 'Company email', key: 'Company email'},
    {value: 'Personal phone', text: 'Personal phone', key: 'Personal phone'},
    {value: 'Company phone', text: 'Company phone', key: 'Company phone'},
    {value: 'LinkedIn', text: 'LinkedIn', key: 'LinkedIn'},
    {value: 'Facebook', text: 'Facebook', key: 'Facebook'},
    {value: 'Twitter', text: 'Twitter', key: 'Twitter'},
];

export const SELLER_ANNUAL_REVENUE_OPTIONS: {value: string, text: string, key: string}[] = [
    {value: '< USD $100K/yr', text: '< USD $100K/yr', key: '< USD $100K/yr'},
    {value: 'USD $100-500K/yr', text: 'USD $100-500K/yr', key: 'USD $100-500K/yr'},
    {value: 'USD $500K-1M/yr', text: 'USD $500K-1M/yr', key: 'USD $500K-1M/yr'},
    {value: 'USD $1M-2M/yr', text: 'USD $1M-2M/yr', key: 'USD $1M-2M/yr'},
    {value: 'USD $2M-5M/yr', text: 'USD $2M-5M/yr', key: 'USD $2M-5M/yr'},
    {value: 'USD $5M-10M/yr', text: 'USD $5M-10M/yr', key: 'USD $5M-10M/yr'},
    {value: 'USD $1M-20M/yr', text: 'USD $1M-20M/yr', key: 'USD $1M-20M/yr'},
    {value: 'USD $20M-50M/yr', text: 'USD $20M-50M/yr', key: 'USD $20M-50M/yr'},
    {value: '> USD 50M/yr', text: '> USD 50M/yr', key: '> USD 50M/yr'},
];